# -*- mode: ruby -*-
# # vi: set ft=ruby :
      
Vagrant.configure("2") do |config|
  config.vm.box = "precise"
  config.vm.box_url = "http://cloud-images.ubuntu.com/vagrant/precise/current/precise-server-cloudimg-amd64-vagrant-disk1.box"
			   
  config.vm.define :chef_server do |chef_server|
    chef_server.vm.box = "precise"
    chef_server.vm.host_name = "chef_server"
    chef_server.vm.network  :private_network, ip: "192.168.33.10"
				          
    chef_server.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "1024"]
    end
  end 
end			   
				  
						

